# Generated by Django 5.1.2 on 2024-10-25 23:33

import django.contrib.postgres.fields.ranges
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_range_merge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("time_range", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
            ],
        ),
    ]
